### PR TITLE
can find any job, not just within the top 25

### PR DESCRIPTION
**Pull request by josephecombs**

### CODE REVIEW

**Comment by thegengen** [comment]
This is a good change, but I think it should replace what's in `PrinterJobCollection#find`. Is there any reason to add a new method instead of replacing that one?

**Comment by josephecombs** [comment]
I agree that the method should be moved.  Are you in favor of adopting a pattern borrowed from Rails whereby #find either returns an object raises an exception, and find_by_id returns an object or returns false?

**Comment by thegengen** [comment]
I don't think I want that change since it would break the existing API in a pretty significant way. 

Can you give me some scenarios where you're fetching a print job and you'd want to get an exception if it's not present?

I think that the safer ways to get that behavior are:
- Some kind of configuration setting for the client.
- Defining a method like find! instead. -- even though that's the exact opposite of what Rails does with find.

If I were starting over I'd probably do what you're suggesting too, but I'm not sure I want to break the gem like this. Again, feel free to provide use cases if there's something I'm missing.

**Comment by josephecombs** [comment]
I agree, it's a nice to have and not a requirement.  I'm writing changes to these pull requests and I should have updates later today or tomorrow.

**Pull request merged**
